# Cloud Build configuration for ETL Pipeline
steps:
  # Paso 1: Construir imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/data-engineer-gcp-469614/etl-pipeline:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/data-engineer-gcp-469614/etl-pipeline:latest'
      - '.'

  # Paso 2: Subir imagen al registro
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/data-engineer-gcp-469614/etl-pipeline:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/data-engineer-gcp-469614/etl-pipeline:latest']

  # Paso 3: Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'etl-pipeline'
      - '--image'
      - 'gcr.io/data-engineer-gcp-469614/etl-pipeline:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'

# Imágenes que se construyeron
images:
  - 'gcr.io/data-engineer-gcp-469614/etl-pipeline:$COMMIT_SHA'
  - 'gcr.io/data-engineer-gcp-469614/etl-pipeline:latest'